/*!
 * Generated by ActivePresenter 4.0.2 HTML5 (2014.10.08)
 */
﻿/*!
 * Atomi HTML5 Player - Template parameters
 * Copyright (c) Atomi Systems, Inc. All rights reserved.
 * http://atomisystems.com
 * Created: 2008/01/20
 * Modified: 2013/11/01
 */

var PrezInfo = {
	Name:"relative clauses",
	Description:"",
	Date1: "11/5/2014",
	Author:"joaquin",
	Copyright:"",
	Homepage:"",
	RLVersion: "4.0.2",
	AppHomePage: "http://atomisystems.com",
	ViewPort: {width:1362, height:708},
	Language: "en",
	TextDir: "ltr",
	Generator: "ActivePresenter 4.0.2"
};

var Options = {"opmodes":2,"language_id":60,"report_format":0,"report_value":"txusezun@hotmail.com","pass_condition":2,"zoom_percent":100,"ShowReport":true,"ExportHTML5":true,"UseFlashPlayer":true,"pass_value":58,"report_method":0,"FlashABSpeed":0,"AllowNavigate":false,"test_max_time":0,"UseSilverlight":false,"image_format":"png","ConfirmRestart":true,"HilightFocus":false,"UseAccText":false,"ScormScorePercent":false};
var TemplateParams = {
   IniVolume:80,
   IniCCShow:0,
   HighLevelStepText:1,
   SlideListPos:5,
   ShowDuration:2,
   ShowSlideAsGroup:1,
   ToolbarHeight:28,
   ImagePath:"player/images/",
   IniSlideNotesShow:0,
   AlwaysShowSlideNotes:0,
   SlideNotesPos:2,
   IniAutoFit:1,
   ShowDetailedStepsInPractice:1,
   AlwaysShowSlideList:1,
   IniSlideListShow:1,
   DockPaneSize:250,
   NavInPractice:1
}
;
var bSendToLMS = false;
 
var PlayModes = {
	DEMO:	1,
	TUT:	2,
	PRAC:	4,
	TEST:	8
};

var UIPos = {
	//These correspond to value list in manifest
	TOP: 0,
	LEFT: 1,
	RIGHT: 2,
	BOTTOM: 3,
	FLOATING: 4,
	NONE: 5
};